#!/bin/sh

FILES=$(git diff --diff-filter=d --name-only origin/develop | grep -E '\.less$')
if [ -n "$FILES" ]; then
  npx stylelint --aei $FILES --custom-formatter=./stylelint-formatter/index.js -o ./dist/sma-ui-mfe-main-app-reports/stylelint-report.html
else
  echo "No files found into diff with develop for lint with Stylelint."
  exit 0
fi
