#!/usr/bin/env bash

FILES=$(git diff --diff-filter=d --name-only origin/develop | grep -E '\.less$')
if [ -n "$FILES" ]; then
  mkdir -p dist/stylelint && npx stylelint  --aei $FILES --custom-formatter ./stylelint-formatter.js
else
  echo "No files found into diff with develop for lint with Stylelint."
  exit 0
fi
