#!/bin/sh

FILES=$(git diff --diff-filter=d --name-only origin/develop | grep -E '\.less$')
if [ -n "$FILES" ]; then
  npx stylelint --aei $FILES --custom-formatter ./stylelint-formatter.js -o ./dist/stylelint/only-changed-develop-report.html
else
  echo "No files found into diff with develop for lint with Stylelint."
  exit 0
fi
