import { NgModule } from '@angular/core';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import {
  PrizmButtonComponent,
  PrizmCheckboxComponent,
  PrizmColumnSettingsComponent,
  PrizmDateTimeRange,
  PrizmDay,
  PrizmDayRange,
  PrizmDialogComponent,
  PrizmDropdownHostModule,
  PrizmHintDirective,
  PrizmIndicatorComponent,
  PrizmInputCommonModule,
  PrizmInputLayoutDateModule,
  PrizmInputLayoutDateRangeModule,
  PrizmInputLayoutDateTimeModule,
  PrizmInputIconButtonComponent,
  PrizmInputLayoutDateComponent,
  PrizmInputLayoutDateRangeComponent,
  PrizmInputLayoutDateTimeRangeComponent,
  PrizmInputLayoutDateTimeRangeModule,
  PrizmInputLayoutMonthRangeComponent,
  PrizmInputLayoutTimeModule,
  PrizmInputLayoutMonthModule,
  PrizmInputMultiSelectComponent,
  PrizmInputMultiSelectModule,
  PrizmInputNumberModule,
  PrizmInputSelectModule,
  PrizmInputTextModule,
  PrizmLoaderComponent,
  PrizmMonth,
  PrizmMonthRange,
  PrizmPaginatorComponent,
  PrizmPanelComponent,
  PrizmProgressModule,
  PrizmScrollbarModule,
  PrizmSelectInputComponent,
  PrizmSidebarComponent,
  PrizmSplitterModule,
  PrizmStickyModule,
  PrizmSwitcherComponent,
  PrizmTableModule,
  PrizmTabsModule,
  PrizmToastModule,
  PrizmToggleComponent,
  PrizmTooltipModule,
  PrizmTreeModule,
  PrizmCardComponent,
  PrizmDropdownControllerDirective,
  PrizmRadioButtonComponent,
  PrizmBreadcrumbDirective,
  PrizmBreadcrumbsComponent,
  PrizmStepperModule,
} from '@prizm-ui/components';
import { PrizmFlagIconsComponent } from '@prizm-ui/flag-icons';
import { PrizmDestroyService } from '@prizm-ui/helpers';
import { PrizmIconsComponent } from '@prizm-ui/icons';
import { TuiDay } from '@taiga-ui/cdk';
import { SmaPrizmDateTime } from '../directives/date/date-time.types';

export type PrizmDateTypes =
  | TuiDay
  | PrizmDay
  | PrizmDayRange
  | SmaPrizmDateTime
  | PrizmDateTimeRange
  | PrizmMonth
  | PrizmMonthRange;

@NgModule({
  imports: [
    FormsModule,
    ReactiveFormsModule,
    PrizmTableModule,
    PrizmScrollbarModule,
    PrizmCheckboxComponent,
    PrizmStickyModule,
    PrizmButtonComponent,
    PrizmInputTextModule,
    PrizmIconsComponent,
    PrizmPaginatorComponent,
    PrizmInputSelectModule,
    PrizmPanelComponent,
    PrizmToggleComponent,
    PrizmTabsModule,
    PrizmDropdownHostModule,
    PrizmLoaderComponent,
    PrizmSelectInputComponent,
    PrizmInputMultiSelectModule,
    PrizmInputLayoutDateModule,
    PrizmFlagIconsComponent,
    PrizmInputLayoutDateRangeModule,
    PrizmDialogComponent,
    PrizmInputLayoutDateComponent,
    PrizmColumnSettingsComponent,
    PrizmSwitcherComponent,
    PrizmTooltipModule,
    PrizmInputMultiSelectComponent,
    PrizmInputLayoutDateRangeComponent,
    PrizmSidebarComponent,
    PrizmToastModule,
    PrizmInputLayoutDateTimeModule,
    PrizmInputCommonModule,
    PrizmInputIconButtonComponent,
    PrizmInputLayoutMonthModule,
    PrizmHintDirective,
    PrizmTreeModule,
    PrizmInputNumberModule,
    PrizmInputLayoutDateTimeRangeModule,
    PrizmProgressModule,
    PrizmInputLayoutMonthRangeComponent,
    PrizmInputLayoutDateTimeRangeComponent,
    PrizmCardComponent,
    PrizmDropdownControllerDirective,
    PrizmRadioButtonComponent,
    PrizmBreadcrumbDirective,
    PrizmBreadcrumbsComponent,
    PrizmStepperModule,
    PrizmIndicatorComponent,
  ],
  exports: [
    FormsModule,
    ReactiveFormsModule,
    PrizmTableModule,
    PrizmScrollbarModule,
    PrizmCheckboxComponent,
    PrizmStickyModule,
    PrizmButtonComponent,
    PrizmInputTextModule,
    PrizmIconsComponent,
    PrizmPaginatorComponent,
    PrizmInputSelectModule,
    PrizmPanelComponent,
    PrizmToggleComponent,
    PrizmTabsModule,
    PrizmDropdownHostModule,
    PrizmLoaderComponent,
    PrizmSelectInputComponent,
    PrizmInputMultiSelectModule,
    PrizmInputLayoutDateModule,
    PrizmFlagIconsComponent,
    PrizmInputLayoutDateRangeModule,
    PrizmDialogComponent,
    PrizmInputLayoutDateComponent,
    PrizmColumnSettingsComponent,
    PrizmSwitcherComponent,
    PrizmTooltipModule,
    PrizmInputMultiSelectComponent,
    PrizmInputLayoutDateRangeComponent,
    PrizmSidebarComponent,
    PrizmToastModule,
    PrizmInputLayoutDateTimeModule,
    PrizmInputCommonModule,
    PrizmInputIconButtonComponent,
    PrizmInputLayoutMonthModule,
    PrizmHintDirective,
    PrizmTreeModule,
    PrizmInputNumberModule,
    PrizmInputLayoutDateTimeRangeModule,
    PrizmProgressModule,
    PrizmInputLayoutTimeModule,
    PrizmInputLayoutMonthRangeComponent,
    PrizmInputLayoutDateTimeRangeComponent,
    PrizmSplitterModule,
    PrizmCardComponent,
    PrizmDropdownControllerDirective,
    PrizmRadioButtonComponent,
    PrizmBreadcrumbDirective,
    PrizmBreadcrumbsComponent,
    PrizmStepperModule,
    PrizmIndicatorComponent,
  ],
  providers: [PrizmDestroyService],
})
export class PrizmSharedModule {}
